config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get 'sessions/new'
  get "homes/about"
  get "homes/help"

  resources :homes
  resources :products

  resources :users do
    get "checkout" => "users#checkout"
    get "products" => "users#show_products"
    get "products/:id" => "products#show"
    resources :product_bases
    get "update_basket" => "users#update_basket"
    get "manage" => "product_bases#manage"
    get "/manage/checkouts/:product_base_id/new" => "checkouts#new"
    post "/manage/checkouts" => "checkouts#create" 
    get "/manage/checkouts/:id" => "checkouts#show"
    get "/manage/checkouts/:id/edit" => "checkouts#edit", as: :edit_checkout
    patch "/manage/checkouts/:id/update" => "checkouts#update", as: :update_checkout
  end

  resources :product_bases

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :roles
  has_many :products 

  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :password, presence: true, :if => :password
  validates :password_confirmation, presence: true, :if => :password_confirmation
  validates_length_of(:password, minimum: 6)
  validates_length_of(:password_confirmation, minimum: 6)

  validates(:name, presence: true)
  validates(:email, presence: true)
  validates_length_of(:name, maximum: 100)
  validates_length_of(:email, maximum: 100)

  validates(:email,{format: {with: VALID_EMAIL_REGEX}, uniqueness: true})

  has_secure_password

  def has_role?(role_name)
    if (self.roles.find_by(name: role_name).nil?)
      return false 
    end
    true 
  end

  def add_role(role_name)
    self.roles << Role.find_by(name: role_name)
    self.save
  end

  def get_total_prices
    @total_price = 0
    self.products.each do |product|
      item_checkout = product.product_base.checkout
      if (!item_checkout.nil?)
        new_price = item_checkout.scan(product) 
        @total_price = @total_price + product.quantity * new_price 
      else
        @total_price = @total_price + product.quantity * product.price 
      end
    end 
    @total_price
  end

  def add_to_basket(product_code, product_quantity)
    product_base = ProductBase.find_by(product_code: product_code)
    remaining_quantity = product_base.quantity_in_store - product_quantity
    # Checking if the product already exists in the user's basket
    product = self.products.find_by(product_code: product_code)
    if (product.nil?)
      new_product = product_base.products.create(user_id: self.id, quantity: product_quantity, :product_code => product_code, :name => product_base.name, :price => product_base.price)
    else
      product.update_attribute(:quantity, product.quantity+product_quantity )
    end
    product_base.update_attribute(:quantity_in_store, remaining_quantity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action  :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @user_has_role_admin = @user.has_role?("Admin")
  end

  def update_basket 
    @user = User.find(params[:user_id])
    @product_quantity = params[:product_quantity].to_i
    @product_code = params[:product_code].to_i
    respond_to do |format|
      if @user.add_to_basket(@product_code, @product_quantity)
        format.html{ redirect_to user_product_bases_path(@user), notice: "You have added the products!" }
        format.json{ head :no_content}
      else
        format.html{ redirect_to user_product_bases_path(@user), notice: "You have added the products!" }
        format.json{ head :no_content}
      end
    end
  end

  def checkout
    @user ||= User.find(params[:user_id])
    @products = @user.products
    @total_price = @user.get_total_prices
  end

  def show_products 
    @user = User.find(params[:user_id])
    @redirect_from_product_bases = params[:from_product_bases]
    @products = User.find(params[:user_id]).products 
  end

  def list_products 
    @user = User.find(params[:user_id])
    @products = User.find(params[:user_id]).products
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.add_role("Individual")
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, json: @user.password }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update 
    # You are not allowed to update your passwords in the edit 
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    respond_to do |format|
      if @user.update_attribute(:name, params[:user][:name]) && @user.update_attribute(:email, params[:user][:email])
        format.html { redirect_to @user, notice: "Successfully updated!"}
        format.json { render :show, status: :ok, location: @user}
      else
        format.html { render :edit, notice: "not working bro"}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:product_code, :product_quantity, :name, :email, :password, :password_confirmation)
    end

    def find_routes 
      @current_uri = request.env["PATH_INFO"]
      path = Rails.application.routes.recognize_path(@current_uri)
      @controller_name = path[:controller]
      @action_name = path[:action] 
    end
  end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/checkout.html.erb
<% # This should display all the products that the user chooses%>

<span> <h3> You have to pay: <%=@total_price.to_s%> </h3> </span>

<br/>
<%=link_to "Pay by One Click", nil, style: "color:white", class: "btn btn-primary btn-sm" %>
<%=link_to "Back", user_products_path(@user) + "?from_product_bases=true", style: "color:white", class: "btn btn-primary btn-sm" %>
<br/>

<h2> Order Detail: </h2>
<table>
  <thead>
    <tr>
      <th>Product Code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Product's total price</th>
    </tr>
  </thead>
  <%@products.each do |product|%>
    <tr>
      <th><%=label_tag("Code",product.product_code)%></th>
      <th><%=label_tag("Name",product.name)%></th>
      <th><%=label_tag("Price",product.get_price)%></th>
      <th><%=label_tag("Quantity",product.quantity)%></th>
      <th><%=label_tag("Total price",product.quantity * product.get_price)%></th>
    </tr>
  <%end%>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user%>
<br/>

<%=link_to "Back", user_path(@user), style: "color:white", class: "btn btn-primary btn-sm" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, style: "color:white", class: "btn btn-primary btn-sm"%></td>
        <td><%= link_to 'Edit', edit_user_path(user), style: "color:white", class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, style: "color:white", class: "btn btn-primary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, style: "color:white", class: "btn btn-primary btn-sm" %>

app/views/users/list_products.html.erb
<h1> List of Products to buy</h1>
<h1>Products</h1>
<%# Create a hidden field to send an ajax request to the server%>

<table>
  <thead>
    <tr>
      <th>Product code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Details</th>
      <th>Quantity</th>
      <th>Add to basket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product|%>
      <tr>
        <th> <%= label_tag("Code", product.product_code, {:id => "product_code"}) %></th>
        <th> <%= label_tag("Name", product.name, {:id => "product_name"}) %></th>
        <th> <%= label_tag("Price", product.price, {:id => "product_price"}) %></th>
        <th> <%= link_to '<button type = "button"> Detail </button>'.html_safe, product_path(product)%> </th>
        <th> <%= text_field_tag("Quantity", nil, placeholder: "How many?", :id => "product_quantity") %>
        <th> <%= button_tag("Add to basket",{:id=>"product_code",:value => product.product_code,:onclick => "update_answers()"})%>
      </tr> 
    <%end%>
  </tbody>
</table>
<%=link_to '<button type = "button"> Back </button>'.html_safe, user_path(@user)%>

<script type = "text/javascript"> 
  // Get the list of products ids and quantities from the hidden fields and add them to it 
  let update_answers = function() {
    console.log("Hello World");
    product_id = document.getElementById("product_id").value;
    product_quantity = document.getElementById("product_quantity").value;
    console.log(product_quantity);
    makeRequest(product_id, product_quantity);
  }

  function makeRequest(product_id, product_quantity) {
    // Create a new xHTTPRequest here
    send_data = JSON.stringfy({product_code: product_code, product_quantity: product_quantity});
    httpRequest = new XMLHttpRequest();
    httpRequest.onreadystatechange = function() {
      if (httpRequest.status == 200) {
        console.log("Successful");
      }
    }
    httpRequest.open('GET', "/users/<%@user.id%>/products/#{product_id}/#{%>)
    httpRequest.send(send_data);
  }
</script>

app/views/users/login.html.erb
<%= form_for(@user, method: :get, url: user_path) do |f|%>

  <%= f.label "Email Address"%>
  <%= f.email_field :email %>

  <%= f.label "Password"%>
  <%= f.password_field :password %>

  <%= f.submit "Log In", class: "btn btn-primary" %>

<%end%>

app/views/users/new.html.erb
<h1> New User</h1>

<%= form_for @user, :method => :post  do |f| %>
  <%= f.label "Full Name"%>
  <%= f.text_field :name %>

  <%= f.label "Email Address"%>
  <%= f.email_field :email %>

  <%= f.label "Password"%>
  <%= f.password_field :password %>

  <%= f.label "Password Confirmation"%>
  <%= f.password_field :password_confirmation %>
  <br/>
  <%= f.submit "Create My Account", class: "btn btn-primary" %>
<%end%>
<br/>
<%= button_to "Back", root_path, method: :get, class: "btn btn-primary" %>

app/views/users/show.html.erb
<%= @controller_name%>
<%= @action_name%>
<p id="notice"><%= notice %></p>
<%= gravatar_for @user%>
<% @user.name %>

<p>
  <strong>User_id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%=link_to "Edit Profile", edit_user_path(@user), style: "color:white", class: "btn btn-sm btn-primary" %>
<%=link_to "View Basket", user_products_path(@user), style: "color:white", class: "btn btn-sm btn-primary" %>
<%=link_to "Start Shopping", user_product_bases_path(@user), style: "color:white", class: "btn btn-sm btn-primary" %>
<% if @user_has_role_admin%>
  <%=link_to "Manage Product Bases", user_manage_path(@user), style: "color:white", class: "btn btn-sm btn-primary" %>
<%end%>

app/views/users/show_products.html.erb
<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product|%>
      <tr>
        <th> <%= label_tag("Code", product.product_code) %></th>
        <th> <%= label_tag("Name", product.name) %></th>
        <th> <%= label_tag("Price", product.price) %></th>
        <th> <%= label_tag("Quantity", product.quantity) %></th>
        <th> <%= link_to("Detail", "/users/#{@user.id}/products/#{product.id}", style: "color:white", class: "btn btn-sm btn-primary")%></th>
        <th> <%= link_to("Remove Order", "/products/#{product.id}", method: 'DELETE', style: "color:white", class: "btn btn-sm btn-primary")%></th>
      </tr> 
    <%end%>
  </tbody>
</table>
<%if @redirect_from_product_bases == "true"%>
  <%= link_to "Back", user_product_bases_path(@user), style: "color:white", class: "btn btn-sm btn-primary" %>
<%else%>
  <%= link_to "Back", user_path(@user), style: "color:white", class: "btn btn-sm btn-primary" %>
<%end%>
<%=link_to "Check Out", user_checkout_path(@user), style: "color:white", class: "btn btn-sm btn-primary"%>

app/views/users/update_basket.html.erb
<%= @user.id%>
<%= @product_code%>
<%= @product_quantity%>