config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get 'sessions/new'
  get "homes/about"
  get "homes/help"

  resources :homes
  resources :products

  resources :users do
    get "checkout" => "users#checkout"
    get "products" => "users#show_products"
    get "products/:id" => "products#show"
    resources :product_bases
    get "update_basket" => "users#update_basket"
    get "manage" => "product_bases#manage"
    get "/manage/checkouts/:product_base_id/new" => "checkouts#new"
    post "/manage/checkouts" => "checkouts#create" 
    get "/manage/checkouts/:id" => "checkouts#show"
    get "/manage/checkouts/:id/edit" => "checkouts#edit", as: :edit_checkout
    patch "/manage/checkouts/:id/update" => "checkouts#update", as: :update_checkout
  end

  resources :product_bases

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/product_bases_controller.rb
class ProductBasesController < ApplicationController
  before_action :set_product_base, only:[:show, :edit, :update, :destroy]
  before_action :set_user, :user_has_role_admin?, only: [:new, :create,:edit,:show]

  def index
    @from_home_page = true 
    if (!params[:user_id].nil?) 
      @user = User.find(params[:user_id])
      @from_home_page = false 
      @user_has_role_admin = @user.has_role?("Admin")
    end
    @product_bases = ProductBase.all 
  end  

  def show
    @from_home_page = true 
    if (!params[:user_id].nil?)
      @user = User.find(params[:user_id])
      @from_home_page = false
    end
  end

  def manage
    @product_bases = ProductBase.all
    @user = User.find(params[:user_id])
  end

  def destroy
    @product_base.destroy
  end

  def new
    @product_base = ProductBase.new
  end

  def edit
    @product_base = ProductBase.new
  end

  def create
    @product_base = ProductBase.new(product_base_params)
    respond_to do |format|
      if @product_base.save
        format.html { redirect_to user_manage_path(@user), notice: 'Product base was successfully created.' }
        format.json { render :show, status: :created, location: user_manage_path }
      else
        format.html { render :new, json: @product_base.errors }
        format.json { render json: @product_base.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if (@product_base.update(product_base_params))
        format.html { redirect_to @product_base, notice: "Successfully updated!"}
        format.json { render :show, status: :ok, location: @product_base}
      else
        format.html { render :edit, notice: "not working bro"}
        format.json { render json: @product_base.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_product_base
    @product_base = ProductBase.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def user_has_role_admin?
    @user_has_role_admin = User.find(params[:user_id]).has_role?("Admin")
  end

  def product_base_params 
    params.require(:product_base).permit(:product_code, :name, :price, :quantity_in_store)
  end
end

app/views/product_bases/_form.html.erb
<%= form_with(model: product_base, url: user_product_bases_path, method: :put, local: true) do |form| %>
  <% if product_base.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_base.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% product_base.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="field">
    <%= form.label "name" %>
    <%= form.text_field :name %>
  </span>

  <span class="field">
    <%= form.label "Product Code" %>
    <%= form.text_field :product_code %>
  </span>

  <span class="field">
    <%= form.label "Quantity In Store" %>
    <%= form.text_field :quantity_in_store %>
  </span>
  <br/>
  <br/>
  <span class="actions">
    <%= form.submit class: "btn btn-primary btn-sm"  %>
  </div>
<% end %>

app/views/product_bases/edit.html.erb
<h1>Editing product base </h1>

<%= render 'form', product_base: @product_base %>
<br/>
<%= link_to 'Back', user_product_basis_path(@user), style: "color:white", class: "btn btn-sm btn-primary"  %>

app/views/product_bases/index.html.erb
<div class = "product-base-page">
<h1> Products list </h1>
<table id = "product-base-table">
  <thead>
    <tr style="outline: solid">
      <th>Product code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Details</th>
      <% if !@from_home_page%>
        <th>Quantity</th>
        <th>Add to basket</th>
      <% end %>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>

    <% @product_bases.each do |product_base|%>
      <tr>
        <th> <%= label_tag("Product Code", product_base.product_code, {:id => "product_code"}) %></th>
        <th> <%= label_tag("Name", product_base.name, {:id => "product_name"}) %></th>
        <th> <%= label_tag("Price", product_base.price, {:id => "product_price"}) %></th>
        <% if @from_home_page%>
          <th> <%= link_to "Details",product_basis_path(product_base), style: "color:white", class: "btn btn-primary btn-sm" %> </th>
        <% else %>
          <th> <%= link_to "Details","/users/#{@user.id}/product_bases/#{product_base.id}", style: "color:white", class: "btn btn-primary btn-sm" %> </th>
          <th> <%= text_field_tag(product_base.product_code, nil,  placeholder: "How many?") %>
        <%end%>
        <% if !@from_home_page%>
          <th> <%= button_tag("Add to basket", type: 'button', offclick: nil, onclick: "javascript:update_answers('#{@user.id}','#{product_base.product_code}','#{product_base.name}')")%>
        <% end%>
      </tr> 
    <%end%> </tbody>
</table>
<br/>
<% if !@from_home_page%>
  <%= link_to "Back", user_path(@user), style: "color:white", class: "btn btn-primary" %>
  <%= link_to "View Basket", user_products_path(@user) + "?from_product_bases=true", style: "color:white", class: "btn btn-primary" %>
<%else%>
  <%= link_to "Back", homes_path, style: "color:white", class: "btn btn-primary" %>
<%end%>
</div>

<script type = "text/javascript"> 
  let update_answers = function(user_id, product_code, product_name) {
    product_quantity = document.getElementById(product_code).value;
    makeRequest(user_id, product_code, product_quantity, product_name);
    console.log(user_id, product_code, product_quantity, product_name);
  }

  // Send request to update the basket of the user
  let makeRequest = function(user_id, product_code, product_quantity, product_name) {
    // Create a new xHTTPRequest here 
    httpRequest = new XMLHttpRequest();
    url_path = "/users/" + user_id + "/update_basket?product_code=" + product_code + "&product_quantity=" + product_quantity;
    httpRequest.open("GET", url_path);
    httpRequest.send();
    httpRequest.onreadystatechange = function() {
      if (httpRequest.status == 200) {
        alert(`You have sucessfully purchased ${product_quantity} ${product_name}`);
      }
    }
  }
</script>

app/views/product_bases/manage.html.erb
<div class = "product-base-page">
<h1> Products list </h1>
<table id = "product-base-table">
  <thead>
    <tr style="outline: solid">
      <th>Product code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Details</th>
      <th>Promotion</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>

    <% @product_bases.each do |product_base|%>
      <tr>
        <th> <%= label_tag("Product Code", product_base.product_code, {:id => "product_code"}) %></th>
        <th> <%= label_tag("Name", product_base.name, {:id => "product_name"}) %></th>
        <th> <%= label_tag("Price", product_base.price, {:id => "product_price"}) %></th>
        <th> <%= link_to "Details", user_product_basis_path(user_id: @user.id, id: product_base.id), style: "color:white", class: "btn btn-primary btn-sm" %> </th>
        <% if !product_base.checkout.nil?%>
        <th> <%= link_to product_base.checkout.name, "/users/#{@user.id}/manage/checkouts/#{product_base.checkout.id}", style: "color:white", class: "btn btn-primary btn-sm" %></th>
        <% else%>
        <th> <%= link_to "New Rule", "/users/#{@user.id}/manage/checkouts/#{product_base.id}/new", style: "color:white", class: "btn btn-primary btn-sm" %></th>
        <%end%>
      </tr> 
    <%end%>
  </tbody>
</table>
<br/>
<th> <%= link_to "New Product Base", new_user_product_basis_path(@user), style: "color:white", class: "btn btn-primary btn-sm" %> </th>
<th> <%= link_to "Back", user_path(@user), style: "color:white", class: "btn btn-primary btn-sm" %> </th>
</div>

app/views/product_bases/new.html.erb
<h1> New Product Base</h1>

<%= form_for @product_base, :url => "/users/#{@user.id}/product_bases" ,:method => :post  do |f| %>
  <%= f.label "Name"%>
  <%= f.text_field :name %>

  <%= f.label "Product Code"%>
  <%= f.text_field :product_code %>

  <%= f.label "Quantity in Store"%>
  <%= f.text_field :quantity_in_store %>

  <%= f.label "price"%>
  <%= f.text_field :price %>
  <br/>
  <%= f.submit "Create new product base", class: "btn btn-primary" %>
<%end%>
<br/>
<%= button_to "Back", root_path, method: :get, class: "btn btn-primary" %>

app/views/product_bases/show.html.erb
<h1> Product Information </h1>
<span> <strong> Product Code: </strong></span>
<%= @product_base.product_code%> <br/>
<span> <strong> Product Name: </strong></span>
<%= @product_base.name%> <br/>
<span> <strong> Product Price: </strong></span>
<%= @product_base.price%> <br/>
<span> <strong> Quantity In Store: </strong></span>
<%= @product_base.quantity_in_store%> <br/>
<br/>
  <%= link_to "Edit", edit_user_product_basis_path(user_id: @user.id, product_base_id: @product_base.id) , style: "color:white", class: "btn btn-primary"%>
<% if @from_home_page%>
  <%= link_to "Back", product_bases_path, style: "color:white", class: "btn btn-primary"%>
<%else%>
  <%= link_to "Back", user_manage_path(@user), style: "color:white", class: "btn btn-primary"%>
<%end%>