config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get 'sessions/new'
  get "homes/about"
  get "homes/help"

  resources :homes
  resources :products

  resources :users do
    get "checkout" => "users#checkout"
    get "products" => "users#show_products"
    get "products/:id" => "products#show"
    resources :product_bases
    get "update_basket" => "users#update_basket"
    get "manage" => "product_bases#manage"
    get "/manage/checkouts/:product_base_id/new" => "checkouts#new"
    post "/manage/checkouts" => "checkouts#create" 
    get "/manage/checkouts/:id" => "checkouts#show"
    get "/manage/checkouts/:id/edit" => "checkouts#edit", as: :edit_checkout
    patch "/manage/checkouts/:id/update" => "checkouts#update", as: :update_checkout
  end

  resources :product_bases

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all 
  end

  def about
  end

  def help
  end
  
  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)
    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home, style: 'color:white', class: "btn btn-lg btn-primary" %> |
<%= link_to 'Back', homes_path, style: 'color:white', class: "btn btn-lg btn-primary" %>

app/views/homes/index.html.erb
<div class = "center jumbotron">
  <h2> Welcome to the Logivan App </h2>

  <h2>
    <div id = "container"> 
      <span class = "main-button">
          <%=link_to "START SHOPPING", product_bases_path + "?from_homepage=true", method: :get, style: 'color:#FFFFFF;', class: "btn btn-lg btn-primary"%>
          <%=link_to "LOG IN", login_path, method: :get,style: 'color:white', class: "btn btn-lg btn-primary"%>
      </span> 
    </div>
  </h2>
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path, style: "color:white", class: "btn btn-primary" %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home), style: "color:white", class: "btn btn-primary" %> |
<%= link_to 'Back', homes_path, style: "color:white", class: "btn btn-primary" %>