config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get 'sessions/new'
  get "homes/about"
  get "homes/help"

  resources :homes
  resources :products

  resources :users do
    get "checkout" => "users#checkout"
    get "products" => "users#show_products"
    get "products/:id" => "products#show"
    resources :product_bases
    get "update_basket" => "users#update_basket"
    get "manage" => "product_bases#manage"
    get "/manage/checkouts/:product_base_id/new" => "checkouts#new"
    post "/manage/checkouts" => "checkouts#create" 
    get "/manage/checkouts/:id" => "checkouts#show"
    get "/manage/checkouts/:id/edit" => "checkouts#edit", as: :edit_checkout
    patch "/manage/checkouts/:id/update" => "checkouts#update", as: :update_checkout
  end

  resources :product_bases

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class = "navbar navbar-fixed-top navbar-inverse">
      <div class = "container">
        <%= link_to 'Logivan_app', '#', id: "logo"%>
        <nav>
          <ul class = "nav navbar-nav navbar-right">
            <li><%= link_to "HOME", "/", class: "btn-lg"%></li>
            <li><%= link_to "ABOUT", homes_about_path, class: "btn-lg"%></li>
            <li><%= link_to "HELP", homes_help_path, class: "btn-lg"%></li>
            <li><%= link_to "LOG IN", login_path, class: "btn-lg"%></li>
            <li><%= link_to "SIGN UP", new_user_path, class: "btn-lg"%></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>